notaryproject/notation

README.md
Add info to help folks find the prototypes 
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
=> Add root readme info

README.md
I updated the table of contents to include the TUF prototype.
=> Add TUF prototype to the readme

tuf-design.md
Update the introduction and make edits for grammar and clarity
=> Update tuf-design introduction

tuf-design.md
This adds a section about namespaces and how to manage tags that change as images are moved across registries.
=> Describe namespaces and changing tags

key-management.md
This document describes how TUF handles key management and distribution.
=> Key management Description

Makefile, cmd/docker-nv2/push.go, go.mod, go.sum
- Resolve #47 
- Better makefile
- Update the notary library for the latest API changes: https://github.com/notaryproject/notary/pull/2
=> Minor prototype update

cmd/docker-nv2/pull.go
=> Persist signatures when pulling

cmd/docker-nv2/config/config.go
=> Create parent folders before config file creation

tuf-design.md
Update links to the specification (rendered version) and TAP 16: Snapshot Merkle Trees
=> Update links in tuf-design.md

CODE_OF_CONDUCT.md, README.md
- Added CODE_OF_CONDUCT.md file
- Updated README.md to reflect the new CODE_OF_CONDUCT.md file
Signed-off-by: Terence Truong <48969648+terencet-git@users.noreply.github.com>
=> Adding Code of Conduct file and updating README.md to reflect new change

pkg/registry/repository.go
=> Fix location parsing

pkg/registry/auth.go
=> Correct auth flow

cmd/notation/sign.go
=> No default push on local sign

pkg/registry/auth.go
=> Support anonymous access

RELEASE_CHECKLIST.md
=> Document release checklist

.github/workflows/release-github.yml, RELEASE_CHECKLIST.md
=> Improve release pipeline

internal/version/version.go
=> Bump version to v0.7.1-alpha.1

go.mod, go.sum, pkg/registry/repository.go
=> Update artifact spec

.goreleaser.yml
=> No auto-publish on release

README.md, docs/hello-signing.md
=> Update doc for v0.7.1-alpha.1

README.md
Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
To fix: https://github.com/notaryproject/notation/issues/190
=> fix mistaken download URL

cmd/notation/cert.go, go.mod, go.sum
Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>
=> use notation-core-go crypto utils

specs/notation-cli.md
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
=> Sorting commands for clarity #221

README.md
Signed-off-by: Juncheng Zhu <junczhu@microsoft.com>
=> Doc update README for codecov badge

docs/hello-signing.md, go.mod, go.sum
Signed-off-by: Patrick Zheng [patrickzheng@microsoft.com](mailto:patrickzheng@microsoft.com)
=> updated hello-signing.md to include certificate chain and COSE envelope

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/dev-release.yml, .github/workflows/release-github.yml, go.mod
=> feat: update to go 1.19 (#327)

docs/hello-signing.md
=> doc: update doc for verify command

go.mod, go.sum
=> build: update notation-core-go to use main branch

README.md
Signed-off-by: David Tesar <david.tesar@microsoft.com>
=> add goreport badge

.github/workflows/scorecard.yml, README.md
Signed-off-by: David Tesar <david.tesar@microsoft.com>
=> add openssf scorecard

cmd/notation/cert.go, internal/certificate/cert.go
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>
=> updated notation certificate command

RELEASE_CHECKLIST.md
Signed-off-by: David Tesar <david.tesar@microsoft.com>
=> update release process

cmd/notation/cert/delete.go, cmd/notation/key.go, specs/commandline/certificate.md, specs/commandline/key.md
=> feat: remove notation certificate/key rm alias

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/dev-release.yml, .github/workflows/release-github.yml, go.mod, test/e2e/go.mod, test/e2e/plugin/go.mod
Fixes #535 
I wasn't able to find a `Dockerfile`. If you could guide me, I will change it there too @shizhMSFT
=> bump: go 1.19 to 1.20

internal/version/version.go
Upgrading the notation version to v.1.0.0-rc.2
=> build: upgrade version to v1.0.0-rc.2

cmd/notation/manifest.go
This PR adds check on user input digest and resolved digest.
=> fix: added digest check on resolve ref

internal/version/version.go
Update:
- update version for rc.7 release
=> build: bump version to rc.7

go.mod, go.sum
- oras-credential-go release note: https://github.com/oras-project/oras-credentials-go/releases/tag/v0.3.1
Resolves #801 
=> fix: legacy docker config support

specs/commandline/list.md
=> chore: update tag to digest

go.mod, go.sum
=> bump: bump up notation-go

.github/workflows/build.yml
=> fix(ci): update codecov token

go.mod, go.sum, test/e2e/go.mod, test/e2e/go.sum, test/e2e/plugin/go.mod, test/e2e/plugin/go.sum
This PR is for `release-1.2` branch.
=> bump: bump up dependencies

specs/proposals/blob-signing.md
Add the proposal for https://github.com/notaryproject/notation/issues/741
=> docs: add the proposal for Notation blob signing and verification

cmd/notation/blob/policy/init.go, specs/cmd/policy.md, specs/cmd/verify.md
Updates related to trust policy.
=> fix: updates regarding trust policy

specs/cmd/certificate.md
Update the CLI spec to resolve #647 
=> docs: add the cleanup-test command

specs/cmd/blob.md
This PR makes corresponding changes based on https://github.com/notaryproject/notation/blob/main/specs/proposals/blob-signing.md.
=> docs: update blob command spec

README.md
Update community meeting information based on the proposal https://github.com/notaryproject/.github/issues/80. I also raised a CNCF service ticket to update the schedule on CNCF Calendar.
=> chore: update community meeting information
