- prototype-spec.md
This specification describes the queries required for a TUF implementation. I focused on describing processes that would require communication between entities.
The metadata definitions are based on the TUF specification with a couple of minor changes. The exact format of these files isn't as important as the information that's included in them (although they will need some kind of canonicalization for the signatures).
Let me know if anything needs to be further specified. cc @sudo-bmitch, @dlorenc, @trishankatdatadog
> Add a specification for the TUF prototype

- cmd/docker-nv2/config/path.go
- cmd/docker-nv2/notary_sign.go
- cmd/docker-nv2/push.go
> Multiple signatures support

- cmd/docker-nv2/notary_sign.go
> Explicit add original references when signing

- .github/ISSUE_TEMPLATE/config.yml
This PR adds a reference to Github discussions when someone tries to create a new issue.
Didn't define templates yet so kept free format issues open for now.
Defining templates allows for automation using github actions. E.g. Agenda items to discuss in meetings etc.
> Add isssue template referring to discussions

- docs/nv2/demo-compose.md
- docs/nv2/sandbox/Dockerfile
* Update to use tree output from https://github.com/oras-project/oras/pull/297
* Update nv2 source branch
* Begin rename from nv2 to notation
Sample output using tree
```
oras discover $IMAGE -o tree
registry.wabbit-networks.io/net-monitor:v1
├── [application/x.example.sbom.v0]sha256:b89becf281d96b32cfed1c8cd2a3e8a856de388fe3670c48f9ba08da32c2480e
│   └── [application/vnd.cncf.notary.v2]sha256:d472fa6e74ff024138eebfa49265389769c5febd98912c3b106d365c35888153
└── [application/vnd.cncf.notary.v2]sha256:4243d006c9546bcb099e3a57e0bf3be7195553662a53254c3f6ed0500d6681f4
```
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
> Update demo compose files to use tree output

- cmd/notation/cert.go
- cmd/notation/common.go
- cmd/notation/key.go
- cmd/notation/main.go
- cmd/notation/plugin.go
- cmd/notation/sign.go
- cmd/notation/verify.go
- go.mod
- internal/cmd/signer.go
- pkg/config/config.go
- pkg/config/map.go
- pkg/config/util.go
- pkg/executor/executor.go
- pkg/signature/kms_jws.go
Adds framework to:
- Add, remove, list kms plugin
- Add kms keys for signing and verification
This is a proof of concept based on the initial hackmd spec. For more details on the implementation refer to https://docs.google.com/document/d/1tDxprA7_H2tVJP0YZFznuTTqDwFP4qks5SaSMaOpS80/edit?usp=sharing.
> feat: add initial framework for notation extensibility

- .github/workflows/upload-release-asset.yml
Resolve https://github.com/notaryproject/notaryproject/issues/120
The new Github action will automatically build binaries when there is a new commit (including PR-merge) on the `feat-kv-extensibility` feature branch, and upload the asset to the dedicated release page.
Format:
- Release tag: [branch name]
- Assets: notation-[branch name]-[YYmmddHHMMSS]-[short commit hash].tar.gz
Sample job: https://github.com/Wwwsylvia/notation/actions/workflows/upload-release-asset.yml
Sample release: https://github.com/Wwwsylvia/notation/releases/tag/feat-kv-extensibility
> Automatically upload release asset for feature branch feat-kv-extensibility

- CONTRIBUTING.md
- cmd/docker-notation/docker/manifest.go
- cmd/docker-notation/pull.go
- cmd/docker-notation/push.go
- cmd/docker-notation/sign.go
- cmd/docker-notation/util.go
- cmd/notation/cert.go
- cmd/notation/manifest.go
- cmd/notation/push.go
- cmd/notation/sign.go
- cmd/notation/verify.go
- go.mod
- go.sum
- internal/cmd/signer.go
- pkg/registry/interface.go
- pkg/registry/repository.go
- pkg/signature/jws.go
This is to allow the client to utilize the latest version of the now renamed notation-go library. It will need another release on main to finalize.
> Update deps links for notation-go

- .github/workflows/release-github.yml
This fixes the go-releaser to automatically attach the binaries.  It needs go 1.18 to understand slices.
> bump to go 1.18

- .github/workflows/add-to-project.yml
This will make it so any time an issue is created in the repository that it will get automatically added with a `needs-triage` label and be added to the Notary-Planning project using the [Add To GitHub Projects Beta action](https://github.com/marketplace/actions/add-to-github-projects-beta).
> Add issues to project action

- specs/directory.md
Resolves #167
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
> Directory Structure Spec

- specs/registry-auth.md
Related to #119
Signed-off-by: Shiwei Zhang shizh@microsoft.com
> Registry Authentication Spec

- specs/notation-cli.md
Closes https://github.com/notaryproject/notation/issues/88
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Baseline CLI reference for subsequent PRs on changes

- specs/notation-cli.md
Updates for #119 
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> notation login CLI

- cmd/notation/cache.go
- cmd/notation/common.go
- cmd/notation/list.go
- cmd/notation/login.go
- cmd/notation/logout.go
- cmd/notation/main.go
- cmd/notation/manifest.go
- cmd/notation/pull.go
- cmd/notation/push.go
- cmd/notation/registry.go
- cmd/notation/sign.go
- cmd/notation/verify.go
- go.mod
- go.sum
- pkg/auth/api.go
- pkg/auth/credential.go
- pkg/auth/native_store.go
- pkg/auth/types.go
- pkg/config/config.go
- pkg/config/docker_config.go
Add support for logging in/out. Related Issue: https://github.com/notaryproject/notation/issues/119
Work need to be done:
test plan:
1. run login cmd
2. run logout cmd
3. run other CMDs, e.g. list/push/pull
3.1 user types username/password explicitly. [expect: user-typed credential is used]
3.2 user doesn't type username/password. [expect: saved credential is used]
4. ~/.notaion/config.json is set up
4.1 both credHelpers and credsStore are configured. [expect: only credHeplers is honored]
4.2 only credsStore is configured. [expect: credsStore is honored]
5. ~/.docker/config.json is set up while ~/.notaion/config.json not
5.1 both credHelpers and credsStore are configured. [expect: only credHeplers is honored]
5.2 only credsStore is configured. [expect: credsStore is honored] …
> [Feature] support notation login

- pkg/auth/credential_test.go
- pkg/auth/native_store_test.go
- pkg/config/docker_config_test.go
Add unit tests for notation login.  https://github.com/notaryproject/notation/pull/218
Coverage:
> test: Add unit tests for notation login

- cmd/docker-notation/sign.go
- cmd/notation/cache.go
- cmd/notation/cert.go
- cmd/notation/cert_gen.go
- cmd/notation/common.go
- cmd/notation/key.go
- cmd/notation/list.go
- cmd/notation/login.go
- cmd/notation/logout.go
- cmd/notation/main.go
- cmd/notation/manifest.go
- cmd/notation/plugin.go
- cmd/notation/pull.go
- cmd/notation/push.go
- cmd/notation/registry.go
- cmd/notation/sign.go
- cmd/notation/verify.go
- internal/cmd/flags.go
- internal/cmd/options.go
- internal/cmd/signer.go
Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>
This PR fixes https://github.com/notaryproject/notation/issues/183 by using `github.com/spf13/cobra` to replace github.com/urfave/cli/v2, which is a cli package also used by [oras-cli](https://github.com/oras-project/oras).
This PR also fixed https://github.com/notaryproject/notation/issues/211, which is caused by `urfave`.
According to the statement from previous PR(https://github.com/notaryproject/notation/pull/250), this is the second PR of the whole series, which updates `cmd/notation`.
As we have discussed in the https://github.com/notaryproject/notation/discussions/251, `docker-notation` may be moved to another repo, so I will left most of the code unchanged.  
Though, I changed `signImage` function of the `docker-notation` cmd only …
> use cobra for notation cli

- specs/registry-auth.md
> Remove credential file from spec

- cmd/notation/registry.go
- pkg/auth/credential.go
- pkg/auth/native_store.go
Backgroud: according to previous design, credentials store config must exist in notation config.json or docker config.json, but you may not need a credentials store config to sign image for local registry. 
Fix: we need to allow empty credentials store config for local reigistry.
Test:
1. sign local registry
2. sign remote registry with username/password
3. sign remote registry without username/password
4. login with credential config
5. login without credential config
6. logout with credential config
7. logout without credential config
Resolves #284 
> fix: allow empty credentials store config

- specs/notation-cli.md
Resovles https://github.com/notaryproject/notation/issues/276
For commands other than `notation login`, we should allow them support `username/password` options even without first-time logging.
Since the `login` command requires `credentialsStore` set up which might be missing for users. So we cannot force users always use `login` to save credentials. Other commands should be able to use the credentials directly from input without `credentialsStore` set up.
Updated commands:
1. sign
2. push
3. pull
4. list
5. cache
6. verify
> doc: add missing username/password options to commands

- internal/version/version.go
Signed-off-by: Yi Zha zhayi@outlook.com
> bump up version to v0.10.0-alpha.3

- cmd/notation/cert_gen.go
- go.mod
- go.sum
This PR updates notation-go to v0.0.0-20220809210532-f0a54093ba32.
1. update directory structure logic: if config file doesn't exist, create the file at user config directory instead of the system directory;
2. dir.Path.Localkey signature has been changed and we need to adapt our code.
> fix: update notation-go

- go.mod
- go.sum
Updated dependencies:
`notation-core-go` `v0.0.0-20220809210532-f0a54093ba32` -> `v0.1.0-alpha.3`
`notation-go` `v0.9.0-alpha.1.0.20220816013743-c350ef73e5f0` -> `v0.10.0-alpha.3`
`oras-go` `v2.0.0-rc.1.0.20220727034506-eb13fdfeefa6` -> `v2.0.0-rc.2`
Signed-off-by: Yi Zha <zhayi@outlook.com>
> Build: Bump dependencies

- cmd/notation/cert.go
- cmd/notation/cert_test.go
removed the expiry flag of 'notation cert generate-test' command
Resolves #312 
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>
> fix: deprecated the expiry flag of notation cert generate-test

- specs/directory.md
Improve readability of directory spec without changing the underlying directory structures.
Resolves #220
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
> doc: improve readability of directory spec

- go.mod
- go.sum
- internal/cmd/flags.go
add config.json `envelopeType` argument support
Test:
1. config: no `envelopeType` or `envelopeType` = "" or `envelopeType` = "jws"  AND cli: notation sign -> JWS format
2. config: no `envelopeType` or `envelopeType` = "" or `envelopeType` = "jws"  AND cli: notation sign `--envelope-type cose` -> COSE format
3. config: `envelopeType` = "cose" AND cli: notation sign -> COSE format
4. config: `envelopeType` = "cose" AND cli: notation sign `--envelope-type jws`-> JWS format
5. config: `envelopeType` = "cosw" AND cli: notation sign -> `Error: signature format cosw not supported`
6. config: `envelopeType` = "cosw" AND cli: notation sign `--envelope-type jws`-> JWS format
> feat: add config.json envelopeType support

- cmd/notation/sign_test.go
- internal/cmd/flags.go
- internal/cmd/signer.go
- internal/envelope/envelope.go
- pkg/configutil/once.go
1. move the envelope format name definition to ./internal/envelope/
2. add default value envelopeType = jws to config.json
> feat: write envelopeType default value to config.json

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/dev-release.yml
- .github/workflows/release-github.yml
- go.mod
update:
1. go.mod
2. github action
Test:
1. unit test work well
2. hello-signing steps work well
Resolves #277
> feat: update to go 1.19

- README.md
Minor updates to README.md.
Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
> fix broken links and refine wording in README.md

- cmd/notation/verify.go
- go.mod
- go.sum
- internal/cmd/signer.go
This PR updates notation cli with the main branch of `notation-core-go` and `notation-go`.
After all PRs merged, I will update go.mod to use main branch.
Test manually on virtual machine.
Now I hard code envelope type to be jws. I will add more envelope types after cose merged.
Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>
> feat:updating go.mod dependencies for alpha4

- cmd/notation/verify.go
- cmd/notation/verify_test.go
- internal/ioutil/print.go
1. Support passing in a reference in the format: registry/repository:v1. Before that, only a reference with digest tag is supported.
2. Refactor the print out format to be more readable.
Success case:
Failure case:
> feat: support tagged reference

- .github/workflows/dev-release.yml
Signed-off-by: David Tesar <david.tesar@microsoft.com>
> add workflow dispatch for dev build

- RELEASE_CHECKLIST.md
Add a note to remind updating the dependencies in go.mod file before starting the release process.
Signed-off-by: Yi Zha <zhayi@outlook.com>
> docs: add a note for dependencies in go.mod file.

- cmd/notation/main.go
- cmd/notation/policy.go
- cmd/notation/policy_test.go
- docs/hello-signing.md
- internal/ioutil/print.go
Add policy commands. It supports adding/updating/reading/deleting policies.
Spec can be found in https://hackmd.io/AP9Xz9AbRpOy6ASpbok23A?view#Manage-Trust-Policy.
Manually tested commands. Test cases can be checked in:  https://hackmd.io/@H7a8_rG4SuaKwzu4NLT-9Q/S1j2Yspxj
This PR depends on https://github.com/notaryproject/notation-go/pull/132, so the build will fail until it's merged.
> feat: add policy command

- cmd/notation/plugin.go
- specs/commandline/plugin.md
According https://github.com/notaryproject/notation/blob/main/specs/commandline/plugin.md.
Updated help message.
Updated spec: replace "\<command>"  with "[command]" because the format is defined in cobra template.
> feat: implement plugin UX

- docs/hello-signing.md
There was a missing `.` in the image tag for `ghcr.io/oras-project/registry:v1.0.0-rc2`. 
See https://github.com/oras-project/distribution/pkgs/container/registry
> Change oras-project/registry tag

- README.md
The current README is broken when trying to use the demo steps
```
docker run -d -p 5000:5000 --platform linux/amd64 ghcr.io/oras-project/registry:v1.0.0-rc2
Unable to find image 'ghcr.io/oras-project/registry:v1.0.0-rc2' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```
There needs to be a dot in the tag.
```
crane ls ghcr.io/oras-project/registry
v0.0.1-alpha
v0.0.2-alpha
v0.0.3-alpha
latest
v1.0.0-rc
v1.0.0-rc.2
```
Tihis PR updates the README:
```
docker run -d -p 5000:5000 --platform linux/amd64 ghcr.io/oras-project/registry:v1.0.0-rc.2
Unable to find image 'ghcr.io/oras-project/registry:v1.0.0-rc.2' locally
v1.0.0-rc.2: Pulling from oras-project/registry
9621f1afde84: Pull complete
26bf68903cef: Pull complete
1991bda9245a: Pull complete …
```
> Fix demo docker pull step

- .dev.goreleaser.yml
- .goreleaser.yml
- Makefile
- cmd/notation/main.go
- cmd/notation/version.go
- internal/version/version.go
- Added version command
- Removed --version flag
- Update Makefile to set GitCommit value by ldflags
- Update the BuildMetadata definition and allow user to override the value by environment variable
Please build it by`make build` command to include git commit information
Example
```
$ ./bin/notation version
Notation: Notary v2, A tool to sign, store, and verify artifacts.
Version:     v0.11.0-alpha.4
Go version:  go1.19
Git commit:  f747031135a6010d92c737ea611276b18f4188d7
```
If it does `not` build by `make build` command, the output will be
```
$ ./bin/notation version
Notation: Notary v2, A tool to sign, store, and verify artifacts.
Version:     v0.11.0-alpha.4
Go version:  go1.19
```
> feat: implement version command

- cmd/notation/login.go
- cmd/notation/logout.go
- cmd/notation/main.go
- specs/commandline/logout.md
implemnt login UI based on https://github.com/notaryproject/notation/blob/main/specs/commandline/login.md fix:
1. added `Login Succeeded` message when login succeeded
2. added username parameter validation
3. removed --plain-http global flag
4. updated spec: removed logout --plain-http & --all flag
Test:
1. login with -u -p flags
2. login with $NOTATION_USERNAME $NOTATION_PASSWORD
3. login with --password-stdin
5. login without username -> `username was not set.`
> feat: implement login/logout UX

- cmd/notation/list.go
- cmd/notation/registry.go
- go.mod
- specs/commandline/list.md
According to: https://github.com/notaryproject/notation/blob/main/specs/commandline/list.md
Updated `list` command output
> feat: implement list command UX

- cmd/notation/sign_test.go
- go.mod
- go.sum
- internal/cmd/flags.go
- internal/cmd/options.go
- internal/cmd/signer.go
- internal/envelope/envelope.go
- internal/envelope/envelope_test.go
- pkg/configutil/once.go
- specs/notation-config.md
1. Add signatureFormat field providing the default value for --signature-format flag in config.json.
2. move GetEnvelopeMediaType() from internal/cmd/signer.go to internal/envelope/envelope.go
Test:
1. signatureFormat = jws, OK
3. signatureFormat = cose, OK
4. signatureFormat = jws, --signature-format=cose, OK
5. signatureFormat = cose, --signature-format=jws, OK
6. signatureFormat  = cose2, cause an `Error: signature format cose2 not supported`
7. signatureFormat = cose2, --signature-format=jws, OK
> feat: add signatureFormat config field

- CONTRIBUTING.md
Signed-off-by: Zach Rhoads <zachary.rhoads@microsoft.com>
> remove reference to nv2

- go.mod
- go.sum
- internal/version/version.go
1. Updating notation-go and notation-core-go dependencies
2. Bumpup version to v0.12.0-beta.1
> Updates for v0.12.0-beta.1 release

- pkg/configutil/util.go
Fixes Issue: https://github.com/notaryproject/notation/issues/410
**Test output**
```
➜  notation git:(fix) ✗ ./notation key ls
NAME   KEY PATH   CERTIFICATE PATH   ID   PLUGIN NAME
➜  notation git:(fix) ✗ ./notation sign --plain-http $IMAGE
Error: default signing key not set. Please set default singing key or specify a key name
```
> Improve error message when default signing key is not set

- specs/commandline/verify.md
Update cli verify spec for UX improvement
> spec: update cli verify spec for UX improvement

- .github/workflows/dev-release.yml
- Added deleting old dev release logic after weekly release.
- Only keep the latest one dev release.
Tested on personal repo.
Resolves https://github.com/notaryproject/notation/issues/448
> feat: delete old dev release

- go.mod
- go.sum
- internal/version/version.go
- update to `notation-core-go` `v1.0.0-rc.1`
- update to `notation-go` `v1.0.0-rc.1`
- update Version to `v1.0.0-rc.1`
> Build: bump up versions for rc.1 release

- cmd/notation/verify.go
> fix: add verification failed log

- cmd/notation/list.go
- cmd/notation/manifest.go
- cmd/notation/sign.go
- cmd/notation/verify.go
This PR refactors the `notation list` command reducing the number of calls to getSignatureRepository() and repo.Resolve().
> update: refactored notation list command

- cmd/notation/login.go
- cmd/notation/logout.go
- cmd/notation/registry.go
- pkg/auth/native_store.go
- pkg/auth/native_store_test.go
- specs/commandline/login.md
- specs/commandline/logout.md
This PR adds logs to the login and logout commands.
This PR is a part of resolving https://github.com/notaryproject/roadmap/issues/71.
> update: added log to notation login and logout commands

- specs/commandline/inspect.md
- specs/notation-cli.md
Use Case / Scenarios:
-     Troubleshooting
-     Auditing
-     If verification of the image digest / signature digest fails due to wrong certificate configuration, user will execute the inspect command to extract the certificate thumb print, a hash of a certificate which is a unique identifier for certificates.
> doc: notation Inspect Command line Spec

- cmd/notation/sign.go
- cmd/notation/verify.go
- specs/commandline/sign.md
- specs/commandline/verify.md
➜  notation git:(main) ✗ ./notation sign $IMAGE
Warning: Always sign the artifact using digest(`@sha256:...`) rather than a tag(`:v1`) because tags are mutable and a tag reference can point to a different artifact than the one signed.
Resolved artifact tag `v1` to digest `sha256:36ca4d6834ed680362327811238b97c687e77c5cf4a04a74d0853d3c0c17e059` before signing.
Successfully signed localhost:6000/net-monitor@sha256:36ca4d6834ed680362327811238b97c687e77c5cf4a04a74d0853d3c0c17e059
➜  notation git:(main) ✗ ./notation verify $IMAGE
Resolved artifact tag `v1` to digest `sha256:36ca4d6834ed680362327811238b97c687e77c5cf4a04a74d0853d3c0c17e059` before verification.
Warning: The resolved digest may not point to the same signed artifact, since tags are mutable.
Successfully verified signature for …
> chore: improve warning message when signing or verifying with tag

- internal/trace/context_test.go
- internal/trace/transport_test.go
- internal/version/version_test.go
> test: add unit test for version & trace packages

- pkg/configutil/once.go
- pkg/configutil/once_test.go
- pkg/configutil/testdata/config.json
- pkg/configutil/testdata/no_default_key_signingkeys/signingkeys.json
- pkg/configutil/testdata/valid_signingkeys/signingkeys.json
- pkg/configutil/util.go
- pkg/configutil/util_test.go
Added error handling.
Added unit test.
#516 
Resolves #525 
> fix: add error handling for LoadConfigOnce()

- cmd/notation/key.go
Don't access value of default pointer if it is nil. This is actually a bug(unable to delete key if defualt key is not present) fix.
Signed-off-by: Pritesh Bandi <pritesb@amazon.com>
> Dont access value of default pointer if it is nil

- specs/commandline/sign.md
updates:
- Update the flag name per community discussion
- Update the description for using OCI image manifest
> doc: update sign.md for OCI image manifest support

- cmd/notation/sign.go
- internal/cmd/flags.go
After discussion with @yizha1, aligning with the spec in this [PR](https://github.com/notaryproject/notation/pull/540).
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>
> chore: update sign command descriptions to align with the spec

- cmd/notation/verify.go
- cmd/notation/verify_test.go
- internal/cmd/flags.go
- internal/ioutil/print.go
- specs/commandline/verify.md
- test/e2e/suite/command/verify.go
This reverts commit 33c228132389d0b0f7b8c13aa25bf124f0d0b485.
We are reverting #527 because we need to write spec first for json output.
> Revert "feat: add support for json output for `notation verify` (#527)"

- cmd/notation/key.go
- specs/commandline/key.md
Fix commands short
* `-p` is used for password so shouldn't use it for plugin
* `-c` is not being used anywhere for `plugin-config`
> fix!: remove short commands

- cmd/notation/registry.go
- cmd/notation/sign.go
- cmd/notation/sign_test.go
- specs/commandline/sign.md
- test/e2e/run.sh
- test/e2e/suite/command/verify.go
> update: changed Sign to use OCI image manifest as default

- specs/commandline/sign.md
Related issue https://github.com/notaryproject/notation/issues/537
Signed-off-by: Pritesh Bandi <priteshbandi@gmail.com>
> feat(doc): simplify signing experience

- specs/commandline/sign.md
This PR partly resolves issue #576 
- Lable flag `--signature-manifest` as experimental feature
- Add notes for using artifact manifest
> doc: add label and notes for experimental features

- cmd/notation/sign.go
This change is based on the spec update: PR #577.
> update: added `[Experimental]` label to the `--signature-manifest` flag

- cmd/notation/sign.go
- cmd/notation/sign_test.go
- internal/cmd/flags.go
- internal/cmd/options.go
- internal/cmd/signer.go
This PR introduces a new option for users to sign using an on-demand key. Users are able to sign without needing to add a key first
This PR intends to address the following issue: #537 
Based on spec changes in #553 
---
Successful sign/verify:
```
c889f3b9d811:notation kodysk$ ./bin/notation sign --plugin com.example.plugin --id example:test-id $IMAGE
Warning: Always sign the artifact using digest(@sha256:...) rather than a tag(:v1) because tags are mutable and a tag reference can point to a different artifact than the one signed.
Successfully signed localhost:5000/net-monitor@sha256:07c30edca95116e23f6a150ba3f7ed296eca71021dba9d9569eb07820f8c0e7d
c889f3b9d811:notation kodysk$ ./bin/notation verify $IMAGE
Warning: Always verify the artifact using digest(@sha256:...) rather than a …
```
> feat: simplify signing experience

- specs/commandline/policy.md
- specs/notation-cli.md
Update:
- Create CLI spec for managing trust policies for phase 1
> doc: create CLI spec for managing trust policies (phase 1)

- cmd/notation/registry.go
This PR: when storing signature using oci image manifest, the Referrers API will be used. If Referrers API is not supported, automatically fallback to use Referrers Tag Schema.
Resolves #575.
> feat: use Referrers API per OCI v1.1 spec 

- specs/commandline/plugin.md
Spec changes to improve the UX for plugin installation and removal using the NotationCLI.
> doc(spec): add subcommands to Notation plugin spec

- cmd/notation/main.go
- cmd/notation/policy/cmd.go
- cmd/notation/policy/import.go
- cmd/notation/policy/show.go
- specs/commandline/policy.md
- test/e2e/suite/command/policy.go
- test/e2e/testdata/config/trustpolicies/invalid_format_trustpolicy.json
This PR implements what's described in [policy.md](https://github.com/notaryproject/notation/blob/18efc3de233ef5eb00e2f32009475a2b8a3eae47/specs/commandline/policy.md).
Resolves #548
> feat: add `show` and `import`  for trust policy management

- cmd/notation/login.go
- go.mod
- go.sum
- test/e2e/internal/notation/host.go
- test/e2e/internal/notation/init.go
- test/e2e/internal/notation/key.go
- test/e2e/suite/command/login.go
- test/e2e/suite/common/common.go
- test/e2e/testdata/config/configjsons/pass_credential_helper_config.json
https://github.com/notaryproject/notation/issues/503
Added e2e tests. The current unit tests don't have RunE() testing code. Adding the unit test could lead to lots of refactoring. I'm happy to help the refactoring and start the unit tests of RunE() but I think it is better to be in a separated PR. Adding lots of unit test refactoring could mess up this PR.
TODO: Seems login requires credential helper. Need to install credential helper as a test step.
> feat: Support username and password prompt in login

- internal/experimental/experimental.go
This PR introduces an environmental variable, `NOTATION_EXPERIMENTAL`, as the switch for experimental features
- If `NOTATION_EXPERIMENTAL` set to `1`, then experimental features are enabled. All experimental features can be used with a prompt in the stderr output:
```console
Caution: This feature is experimental and may not be fully tested or completed and may be deprecated. Report any issues to "https://github/notaryproject/notation"
```
- Otherwise experimental features are disabled, using an experimental command will show
```console
Error: "<COMMAND>" been marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
```
or 
```console
Error: flags(s) --<FLAG1>,--<FLAG2> in "<COMMAND>" been marked as experimental and not enabled …
```
> feat: introduce experimental feature switch

- cmd/notation/sign.go
This PR tries to resolve #615.
> fix: added warning for dangling referrers index deletion

- cmd/notation/policy/cmd.go
- cmd/notation/policy/import.go
- cmd/notation/policy/show.go
- specs/notation-cli.md
This PR removes the preview marks for all policy-related commands.
> doc: remove preview mark from policy commands

- specs/commandline/list.md
- specs/commandline/sign.md
- specs/commandline/verify.md
Update specs for feature sign/verify local images
> doc: update spec for feature sign/verify local images

- cmd/notation/cert/add.go
- cmd/notation/cert/delete.go
- cmd/notation/cert/show.go
- cmd/notation/internal/truststore/truststore.go
This PR aims to resolve #622.
It also adds MarkFlagRequired() to required flags in notation cert command.
> fix: fixing cert command

- cmd/notation/sign.go
Fix https://github.com/notaryproject/notation/issues/584
> doc: add an example to CLI help info for notation sign

- internal/osutil/file_test.go
- pkg/configutil/util_test.go
Fix unit test:
- skip some unit test cases because Windows handles file permissions differently from Unix-based systems, and therefore, using file permissions like 0000, 0600, 0644, or 0700 in tests may not work as expected on Windows.
Test:
- unit test on Windows
- unit test on Linux
Test output:
```
?       github.com/notaryproject/notation/cmd/notation/internal/cmdutil [no test files]
?       github.com/notaryproject/notation/cmd/notation/internal/errors  [no test files]
?       github.com/notaryproject/notation/internal/cmd  [no test files]
?       github.com/notaryproject/notation/cmd/notation/policy   [no test files]
?       github.com/notaryproject/notation/internal/experimental [no test files]
?       github.com/notaryproject/notation/internal/ioutil       [no test files]
ok …
```
> test: skip non-applicable unit tests on Windows

- cmd/notation/inspect.go
- cmd/notation/list.go
- cmd/notation/manifest.go
- cmd/notation/verify.go
- test/e2e/suite/scenario/quickstart.go
Fixes: https://github.com/notaryproject/notation/issues/624
```
➜  notation git:(no-sig) ✗ ./notation inspect $IMAGE 
Warning: Always inspect the artifact using digest(@sha256:...) rather than a tag(:v1) because resolved digest may not point to the same signed artifact, as tags are mutable.
localhost:6000/net-monitor@sha256:52cc9cf0f2e0cadf49337acc7a45a07a2ce5a0ef37702efb0a851884bc32b7b1 has no associated signature
➜  notation git:(no-sig) ✗ ./notation ls $IMAGE      
Warning: Always list the artifact using digest(@sha256:...) rather than a tag(:v1) because resolved digest may not point to the same signed artifact, as tags are mutable.
localhost:6000/net-monitor@sha256:52cc9cf0f2e0cadf49337acc7a45a07a2ce5a0ef37702efb0a851884bc32b7b1 has no associated signature
➜  notation git:(no-sig) ✗ …
```
> fix: Improve output when there is no signature associated

- cmd/notation/inspect.go
- cmd/notation/list.go
- cmd/notation/manifest.go
- cmd/notation/registry.go
- cmd/notation/registry_test.go
- cmd/notation/sign.go
- cmd/notation/sign_test.go
- cmd/notation/verify.go
- go.mod
- go.sum
- internal/cmd/flags.go
- specs/commandline/inspect.md
- specs/commandline/list.md
- specs/commandline/sign.md
- specs/commandline/verify.md
- test/e2e/suite/command/verify.go
- test/e2e/suite/trustpolicy/multi_statements.go
- test/e2e/suite/trustpolicy/registry_scope.go
- test/e2e/suite/trustpolicy/trust_store.go
- test/e2e/suite/trustpolicy/trusted_identity.go
- test/e2e/suite/trustpolicy/verification_level.go
In this PR:
1. Removed Notation's support of signing with OCI artifact manifest. (One can still consume signatures in this type.)
2.  Moved the Referrers API behind experimental as discussed in community meeting. This change takes effect on `sign`, `list`, `inspect`, and `verify` commands. When a user wants to try the Referrers API, they need to set both `NOTATION_EXPERIMENTAL=1` AND `--allow-referrers-api`; if the Referrers API is not supported, fallback to the Referrers tag schema automatically. Otherwise, by default, Notation would use the Referrers tag schema in all commands deterministically.
References: 
https://github.com/opencontainers/distribution-spec/blob/v1.1.0-rc1/spec.md#listing-referrers
https://github.com/opencontainers/distribution-spec/blob/v1.1.0-rc1/spec.md#referrers-ta …
> update: align Notation with OCI specs

- cmd/notation/inspect.go
- cmd/notation/internal/truststore/truststore.go
- specs/commandline/inspect.md
Fixes: https://github.com/notaryproject/notation/issues/611 and https://github.com/notaryproject/notation/issues/635
> fix: update sha1 to sha256 and other chores

- go.mod
- go.sum
- internal/version/version.go
bump up versions and dependencies for rc5
> build: bump up versions and dependencies

- README.md
Added link to official docs to make it easier to find and navigate to when users come across this project and updated link to ACR docs.
> doc: add link to README to docs for clarity

- specs/commandline/certificate.md
- specs/commandline/key.md
Update CLI spec to improve error output in `notation key` and `notation cert` and resolve the UX problem in #604
> doc: improve error output in notation key and notation cert

- .github/workflows/build.yml
- .gitignore
- Makefile
This PR uses the [new Golang feature](https://github.com/golang/proposal/blob/master/design/51430-revamp-code-coverage.md#running-instrumented-applications) to generate coverage report for e2e tests.
For release tagging, the e2e test will be ran based on non-instrumented binary.
To run E2E with test coverage.txt generated locally, try
```bash
make e2e-covdata
```
Resolves #667
> test: generate e2e coverage profile

- Makefile
- building.md
> doc: update building guide

- cmd/notation/sign.go
This quick PR updates the printout logic for `sign`, when user enables `--allow-referrers-api`.
The warning should be valid only when target artifact is stored in a `registry`. 
If the user enables `--oci-layout`, i.e., target artifact is stored in an OCI layout, enabling `--allow-referrers-api` won't take any effect (this is because [oci.Store](https://github.com/oras-project/oras-go/blob/0e20275bbbd71f4619d9c1b9da150c4f586dff3b/content/oci/oci.go#L49) does not support Referrers API yet). In this case, we shouldn't print out the warning.
The fix: During `Sign`, mark flags `--oci-layout` and `--allow-referrers-api` mutually exclusive.
Resolves #683.
> chore: updated warning printout logic for Sign with --allow-referrers-api flag

- test/e2e/suite/trustpolicy/registry_scope.go
This PR fixed the e2e test case, which was failed due to error message updates in notation-go.
> fix: fixed e2e test after dependency bump up

- cmd/notation/login.go
> fix: fix the issue with getting credentials for `docker.io`

- README.md
- specs/commandline/plugin.md
Updating documentation with AWS Plugin support
> fix: Updating documentation with AWS Plugin support

- cmd/notation/login.go
- go.mod
- go.sum
- internal/auth/credentials.go
Fixes: #696 
---
- If the notation config has auth configuration
- Use the notation config for credentials GET, PUT and DELETE
- If the notation config does not have auth configuration, or the the notation config file does not exist
- If the docker config has auth configuration
- Use the notation config for credentials GET, PUT and DELETE
- If there is no authentication configured in the docker config, or the the docker config file does not exist
- If there is a platform-default native keychain installed
- Use the platform-default native keychain for credentials GET, PUT and DELETE
- If there is no platform-default native keychain installed
- GET will always return an empty credential
- PUT will always fail (ErrPlaintextPutDisabled)
- DELETE will result in no operation
> fix: `login` and `logout` will leverage docker config and os default store

- cmd/notation/cert/list.go
- cmd/notation/cert/show.go
- cmd/notation/inspect.go
- cmd/notation/key.go
- cmd/notation/list.go
- cmd/notation/login.go
- cmd/notation/logout.go
- cmd/notation/sign.go
- cmd/notation/verify.go
- go.mod
- go.sum
- internal/cmd/options.go
> feat: add trace for executables

- README.md
> doc: update README to align with the new brand name

- internal/version/version.go
This would mean tagging 80e3fc4e2eeb43ac00bc888cf41101f5c56f1535 as `v1.0.0` to release.
We need at least `4` approvals from `6` maintainers to release `notation v1.0.0`.
The code changes compared to `v1.0.0-rc.7` include:
- #692
- #702
- #703
- #710
- #711
- #712
- #594
- #717
- #716
- #727
- #724
- #731
- #730
- #735
- #739
- #734
- #737
- #745
- #742
- #746
- #744
- #752
- #751
- #754
- #750
**Full Changelog**: https://github.com/notaryproject/notation/compare/v1.0.0-rc.7...80e3fc4e2eeb43ac00bc888cf41101f5c56f1535
Please respond LGTM (approve) or REJECT (request for changes).
> bump: tag and release v1.0.0

- RELEASE_MANAGEMENT.md
update release management for 1.0
> doc: update release management for 1.0

- cmd/notation/policy/import.go
Currently, `notation policy import mypolicy.json` would pop up confirmation before checking whether `mypolicy.json` file exists or valid. 
This PR checks the `mypolicy.json` first and fast fail if the file does not exist or is invalid. If the file exists and valid, then pop up the confirmation to the end user. 
Resolves #773.
> fix: fix trust policy import

- README.md
- specs/commandline/verify.md
The link is broken.
https://notaryproject.dev/docs/quickstart/
> The page that you requested doesn't exist.
> 
> Check the URL's spelling.
> 
> If you think that the page should exist, [create an issue.](https://github.com/notaryproject/notaryproject.dev/issues/new?title=Unexpected%20page-not-found%20error&body=URL%3A%20%0AExpected%20page%3A%20)
So I fixed the link.
https://notaryproject.dev/docs/quickstart-guides/quickstart/
> docs: fix broken links

- .github/workflows/codeql.yml
- .github/workflows/license-checker.yml
- .github/workflows/scorecard.yml
Since notation v1.0.1 is a patch release, we need to create a new branch named `release-1.0` for the release. Current workflows take effect on the `main` branch only. Adding `release-*` as a fix.
> fix: add "release-*" to workflows trigger events

- internal/version/version.go
This would mean tagging e2f4237fb6ac602f68a786afaaf6388fb30b866d as `v1.0.1` to release.
We need at least `4` approvals from `6` maintainers to release `notation v1.0.1`.
The code changes compared to `v1.0.0` include:
- #761
- #762
- #758
- #763
- #760
- #757
- #764
- #714
- #766
- #774
- #775
- #780
- #781
- #782
- #779
- #794
- #795
- #797
- #796
- #789
- #786
- #785
- #799
- #803
- #800
- #776
- #805
- #787
- #810
- #815
- #814
- #813
- #818
- #819
**Full Changelog**: https://github.com/notaryproject/notation/compare/v1.0.0...e2f4237fb6ac602f68a786afaaf6388fb30b866d
Please respond LGTM (approve) or REJECT (request for changes).
> bump: tag and release v1.0.1

- specs/commandline/plugin.md
Update notation plugin spec based on #549 and [PRD](https://hackmd.io/1nQa69DeROyqrO_IB5yGZQ?view#Notation-plugin-management-PRD)
Added new commands and examples including:
- notation plugin install     Install a plugin
- notation plugin ninstall   Uninstall a plugin
Updated the output of `notation plugin list`.
> doc: update plugin spec

- README.md
Similarly to https://github.com/notaryproject/notaryproject.dev/issues/360, 
I attempted to follow the link in the README.md for the quick start guide and discovered the broken link. Linking to the official page.
URL: https://notaryproject.dev/docs/quickstart/
Expected page: https://notaryproject.dev/docs/quickstart-guides/quickstart-sign-image-artifact/
> Correct broken link to quick start guide

- cmd/notation/main.go
- test/e2e/suite/command/verify.go
- test/e2e/suite/plugin/sign.go
Feat:
- added NOTATION_CONFIG and NOTATION_LIBEXEC environment variables
Test:
- notation sign with NOTATION_LIBEXEC locally
- notation verify with NOTATION_CONFIG locally
Resolves #822 
> feat: add notation config environment variable

- internal/trace/transport.go
This PR fixes the `SetHTTPDebugLog` function.
Resolves #851.
> fix: fix bug in `SetHTTPDebugLog`

- cmd/notation/plugin/install.go
- cmd/notation/plugin/list.go
- go.mod
- go.sum
> fix: improve error message for plugin

- internal/version/version.go
This would mean tagging 99ca669edf9e171a912278166323b4c82f3d9706 as `v1.1.0` to release.
We need at least `4` approvals from `6` maintainers to release `notation v1.1.0`.
The code changes compared to `v1.0.1` include:
* feat: update notation cert list command output by @Two-Hearts in https://github.com/notaryproject/notation/pull/798
* fix: Code scanning issues by @JeyJeyGao in https://github.com/notaryproject/notation/pull/799
* fix: legacy docker config support by @JeyJeyGao in https://github.com/notaryproject/notation/pull/803
* build(deps): Bump golang.org/x/net from 0.12.0 to 0.17.0 in /test/e2e by @dependabot in https://github.com/notaryproject/notation/pull/800
* build(deps): Bump oras.land/oras-go/v2 from 2.2.1 to 2.3.0 by @dependabot in …
> bump: tag and release version v1.1.0

- internal/envelope/envelope.go
- internal/envelope/envelope_test.go
- test/e2e/run.sh
- test/e2e/suite/command/cert.go
Previous error message:
```
$ notation sign localhost:5000/hello-app:v1 --plugin azure-kv --id https://x.vault.azure.net/certificates/self-signed-pem/xxx --signature-format xxx
Error: signature format "xxx" not supported
```
Improved error message:
```
$ notation sign localhost:5000/hello-app:v1 --plugin azure-kv --id https://x.vault.azure.net/certificates/self-signed-pem/xxx --signature-format xxx
Error: signature format "xxx" not supported
Please use the supported signature envelope format "jws" or "cose"
```
Test(not related to the fix):
- added unit test and e2e test to reach codecov target 
Resolves #868
> fix: improve error message for --signature-format flag

- cmd/notation/policy/import.go
- cmd/notation/policy/show.go
- test/e2e/suite/command/policy.go
This error message improvement is based on the Notation CLI error message improvement guideline that we defined in #834 
Resolve part of #934 
> fix: error message for trust policy

- .github/workflows/release-github.yml
Fix:
- replace `--rm-dist` with `--clean`
Goreleaser was updated to v6.0.0 in #962. However the flag `--rm-dist` was deprecated in the latest version. Please see the details in the official document: https://goreleaser.com/deprecations/#-rm-dist
Test:
- the test release was successful: https://github.com/JeyJeyGao/notation/actions/runs/9460066788/job/26058225155
> fix(ci): update goreleaser to use --clean flag

- internal/version/version.go
This would mean tagging 3dafd534fe069f2c0ce6127eb33d2e3e476723c3 `v1.1.1` to release.
We need at least `4` approvals from `6` maintainers to release `notation v1.1.1`.
The code changes compared to `v1.1.0` include:
* bump: tag and release version v1.1.0 by @Two-Hearts in https://github.com/notaryproject/notation/pull/876
* build(deps): Bump actions/upload-artifact from 4.2.0 to 4.3.0 by @dependabot in https://github.com/notaryproject/notation/pull/878
* build(deps): Bump codecov/codecov-action from 3.1.4 to 3.1.5 by @dependabot in https://github.com/notaryproject/notation/pull/879
* build(deps): Bump github/codeql-action from 3.23.1 to 3.23.2 by @dependabot in https://github.com/notaryproject/notation/pull/877
* bump: bump up oras-go and image-spec by @Two-Hearts in …
> bump: bump up and vote notation v1.1.1

- internal/version/version.go
This would mean tagging 2f4387276b4a73fb4b81f9499afe0aa156b56218 `v1.2.0-alpha.1` to release.
We need at least `4` approvals from `6` maintainers to release `notation v1.2.0-alpha.1`.
The code changes compared to `v1.1.0` include:
* bump: tag and release version v1.1.0 by @Two-Hearts in https://github.com/notaryproject/notation/pull/876
* build(deps): Bump actions/upload-artifact from 4.2.0 to 4.3.0 by @dependabot in https://github.com/notaryproject/notation/pull/878
* build(deps): Bump codecov/codecov-action from 3.1.4 to 3.1.5 by @dependabot in https://github.com/notaryproject/notation/pull/879
* build(deps): Bump github/codeql-action from 3.23.1 to 3.23.2 by @dependabot in https://github.com/notaryproject/notation/pull/877
* bump: bump up oras-go and image-spec by @Two-Hearts in …
> bump: bump up and vote for v1.2.0-alpha.1

- internal/version/version.go
This would mean tagging 00af3ce880734837f4cad08dd9eb9099ccba5e8f as `v1.2.0-beta.1` to release.
We need at least `4` approvals from `7` maintainers to release `notation v1.2.0-beta.1`.
* bump: bump up and vote for v1.2.0-alpha.1 by @JeyJeyGao in https://github.com/notaryproject/notation/pull/967
* build(deps): Bump github.com/spf13/cobra from 1.8.0 to 1.8.1 by @dependabot in https://github.com/notaryproject/notation/pull/969
* build(deps): Bump actions/checkout from 4.1.6 to 4.1.7 by @dependabot in https://github.com/notaryproject/notation/pull/970
* build(deps): Bump codecov/codecov-action from 4.4.1 to 4.5.0 by @dependabot in https://github.com/notaryproject/notation/pull/972
* build(deps): Bump actions/upload-artifact from 4.3.3 to 4.3.4 by @dependabot in …
> bump: vote for notation v1.2.0-beta.1

- .dev.goreleaser.yml
- .goreleaser.yml
Modify targeted goarch and ignore irelevant configs (e.g windows / arm  and darwi n/ arm)
> build: add support for armv7 binary release

- cmd/notation/sign.go
> chore: move tsa url print out behind -v flag

- internal/version/version.go
This would mean tagging 4700ad6f1bef13e411772d7ae4399f891fc3a6ae as `v1.2.0` to release.
We need at least `4` approvals from `6` maintainers to release `notation v1.2.0`.
* bump: release v1.2.0-rc.1 by @Two-Hearts in https://github.com/notaryproject/notation/pull/1017
* bump: bump up for v1.2.0 stable release by @Two-Hearts in https://github.com/notaryproject/notation/pull/1021
**Full Changelog**: https://github.com/notaryproject/notation/compare/v1.2.0-rc.1...4700ad6f1bef13e411772d7ae4399f891fc3a6ae
Please review the PR and vote by approving.
> bump: release v1.2.0

- internal/version/version.go
This would mean tagging 0d9ceacde56c4b61dbbd7d83a7875986195781f8 as `v1.3.0-rc.1` to release.
We need at least `4` approvals from `6` maintainers to release `v1.3.0-rc.1`.
* build(deps): Bump golang.org/x/net from 0.27.0 to 0.28.0 by @dependabot in https://github.com/notaryproject/notation/pull/1007
* build(deps): Bump actions/upload-artifact from 4.3.4 to 4.3.6 by @dependabot in https://github.com/notaryproject/notation/pull/1009
* build(deps): Bump github/codeql-action from 3.25.15 to 3.26.0 by @dependabot in https://github.com/notaryproject/notation/pull/1010
* bump: upgrade golang version to v1.23 by @Two-Hearts in https://github.com/notaryproject/notation/pull/1019
* build(deps): Bump actions/upload-artifact from 4.3.6 to 4.4.0 by @dependabot in …
> bump: release v1.3.0-rc.1

- internal/trace/context.go
- internal/trace/transport.go
- internal/trace/transport_test.go
- test/e2e/suite/command/verify.go
- test/e2e/suite/plugin/verify.go
Currently the debug log has issues under multi-thread scenarios. This may cause a request log being followed by a response log of another request, which is confusing for log readers.
This PR fixes the issue by labeling the request and response pairs.
This PR does not change any log content. It only makes the log more readable.
> fix: fix debug log

- internal/version/version.go
This would mean tagging d055873720b1a21aa627ee56edc548e0d104002a as `v1.1.2` to release.
This release removed the blob signing docs and fixed the `signingAgent` value to be `notation-go/1.1.2`
We need at least `4` approvals from `6` maintainers to release `v1.1.2`.
* bump: bump up and vote notation v1.1.1 by @JeyJeyGao in https://github.com/notaryproject/notation/pull/963
* fix(docs): remove blob signing docs for `release-1.1` branch by @JeyJeyGao in https://github.com/notaryproject/notation/pull/1013
* bump: update notation-go v1.1.2 by @JeyJeyGao in https://github.com/notaryproject/notation/pull/1041
* bump: dependencies for release-1.1 branch by @JeyJeyGao in https://github.com/notaryproject/notation/pull/1057
**Full Changelog**: …
> bump: release v1.1.2

- internal/version/version.go
This would mean tagging 260968a379b1a3759d8881636595a997780b6e29 as `v1.3.0-rc.2` to release.
We need at least `4` approvals from `6` maintainers to release `v1.3.0-rc.2`.
* bump: release v1.3.0-rc.1 by @Two-Hearts in https://github.com/notaryproject/notation/pull/1056
* fix: cherry pick minor fixes from `main` to `release-1.3` by @Two-Hearts in https://github.com/notaryproject/notation/pull/1110
* bump: bump up dependencies for release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation/pull/1109
* backport: CRL cache with log and E2E tests from `main` to `release-1.3` by @Two-Hearts in https://github.com/notaryproject/notation/pull/1117
* fix: fix context and bump up golang.org/x/net for `release-1.3` branch by @Two-Hearts in …
> bump: release v1.3.0-rc.2

- .github/workflows/release-github.yml
CI:
- Updated the runner version to `ubuntu-24.04` for release pipeline as `ubuntu-20.04` is reaching the end of life on 2025-05-29.
Test:
- `goreleaser` works well in forked repo
Reference: https://en.wikipedia.org/wiki/Ubuntu_version_history#2004
Resolves #1139
> ci: update runner version to ubuntu-24.04

- internal/cmd/flags.go
- pkg/configutil/once.go
- pkg/configutil/once_test.go
- pkg/configutil/util_test.go
Fix:
- the `LoadConfigOnce` function forgets the error and return a nil config and nil error next time. Updated to use `sync.OnceValues` to keep the returned values.
Resolves #1144
> fix: load config error

- .github/workflows/build.yml
- .github/workflows/release-github.yml
- .github/workflows/scorecard.yml
- internal/cmd/flags.go
- pkg/configutil/once.go
- pkg/configutil/once_test.go
- pkg/configutil/util_test.go
This PR cherry picks from main to `release-1.3` branch for `v1.3.0` release.
This PR targets on `release-1.3` branch.
Note: some of the dependabot PRs are not included here because of conflicts. Those bump ups will be included in the bump up  PR of `release-1.3` branch later.
> cherry-pick: cherry pick from main to release-1.3 branch

- specs/commandline/inspect.md
Fix:
- For `text` output, renamed `io.cncf.notary.signingAgent` to `signing agent` to be consistent with the JSON output `signingAgent`.
- For `json` output, rendered timestamp in RFC 3339 with nanoseconds. Timestamp [RFC 3161](https://www.rfc-editor.org/rfc/rfc3161#section-2.4.2) can have a fraction-of-second time value.
> docs: fix inspect command spec

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/release-github.yml
- building.md
- cmd/notation/internal/display/metadata/tree/tree_test.go
- go.mod
- test/e2e/go.mod
- test/e2e/plugin/go.mod
Fix:
- fixed the [testable example](https://go.dev/blog/examples) function name, which is enforced by go v1.24
Bump:
- updated go 1.24
> bump: update go v1.24

- cmd/notation/blob/inspect.go
- cmd/notation/inspect.go
- cmd/notation/inspect_test.go
- cmd/notation/internal/display/handler.go
- cmd/notation/internal/option/format.go
- internal/cmd/flags.go
- specs/commandline/blob.md
- specs/commandline/inspect.md
- test/e2e/suite/command/blob/inspect.go
- test/e2e/suite/command/inspect.go
Update the output format `text` to `tree`.
```
-o, --output string        output format, options: 'json', 'tree' (default "tree")
```
Resolves #1170
> fix: update the output format `text` to `tree`

- cmd/notation/blob/policy/cmd.go
- cmd/notation/blob/policy/import.go
- cmd/notation/blob/policy/show.go
- specs/commandline/blob.md
- test/e2e/suite/command/blob/policy.go
Fix:
- simplified `blob policy show` codes
- improved help docs and error messages
- improved docs
- printed imported blob trust policy file path
Resolves #1134
> fix: blob policy command messages with docs

- internal/version/version.go
This would mean tagging as bb571ddfb04f9d175daf64520fd18e7bea8ecbdf `v1.3.1` to release.
We need at least `4` approvals from `6` maintainers to release `v1.3.1`.
* bump: release v1.3.0 by @Two-Hearts in https://github.com/notaryproject/notation/pull/1149
* bump: bump up dependencies for release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation/pull/1184
**Full Changelog**: https://github.com/notaryproject/notation/compare/v1.3.0...bb571ddfb04f9d175daf64520fd18e7bea8ecbdf
Please review the PR and vote by approving.
> bump: release v1.3.1

- cmd/notation/internal/display/metadata/tree/inspect.go
- cmd/notation/internal/display/metadata/tree/inspect_test.go
The `inspect` command can now output in streaming fashion in `tree` format. Previously, the `inspect` command in `tree` format could only output when all signatures were read, which was not user-friendly when there were many signatures, and users had to wait for a while for the output.
> fix: output in streaming fashion for `inspect` command in `tree` format

- .github/workflows/release-github.yml
- .goreleaser.yml
Release pipeline with **warnings**: https://github.com/notaryproject/notation/actions/runs/13489436510/job/37685202798
Fix:
- locked goreleaser version to v2
- added configuration `version: 2`: https://goreleaser.com/errors/version/?h=configuration+version#unsupported-configuration-version
- updated deprecated 
- `format` option: https://goreleaser.com/deprecations/#archivesformat
- `overrides.format` option: https://goreleaser.com/deprecations/#archivesformat_overridesformat
Test:
- tested release pipeline in forked repo
> fix: goreleaser deprecated options

- internal/version/version.go
This would mean tagging 6c5c35a0207eebf8d4d6d2efad66b798457a6622 as `v2.0.0-alpha.1` to release.
1. Added new command: `notation blob` with subcommands `notation blob sign`, `notation blob verify`, `notation blob policy`, and `notation blob inspect`. It enables blob signing and verification with blob trust policy configuration.
2. Compliant with OCI-1.1 specs, namely [distribution-spec v1.1.1](https://github.com/opencontainers/distribution-spec/tree/v1.1.1) and [image-spec v1.1.1](https://github.com/opencontainers/image-spec/tree/v1.1.1). With the new update, `notation sign` command now stores signatures in the registry as a referrer of the target artifact by default, no extra image index will be created in this case. Removed the deprecated flag `--allow-referrers-api`.
3. Delta CRL …
> bump: release v2.0.0-alpha.1

- cmd/notation/main.go
Go won't run defers if `os.Exit()` is called, so in the case of an error the context cancelation will not run.
> fix: fix main function

- README.md
This PR adds a link to the "Contributing Guide" section in the README file, providing contributors with easy access to the project's contributing guidelines.
**fix #1224**
> docs: add contributing guide link to README.md

- go.mod
- go.sum
Please consider merging this small security patch and then issue a new 1.3.2 release if the `release-1.3` branch is still maintained. Thanks!
> CVE-2025-30204: update golang-jwt

- .github/workflows/build.yml
Add new signed commits in PR on `.github/workflow/build.yml` #1136  with comments.
> ci: add signed commit check

- internal/version/version.go
This would mean tagging 001cc919603c1dc16c6aad387c94b4209cb9c901 as `v1.3.2` to release.
We need at least `4` approvals from `6` maintainers to release `v1.3.2`.
* bump: release v1.3.1 by @Two-Hearts in https://github.com/notaryproject/notation/pull/1186
* CVE-2025-30204: update golang-jwt by @artem-panchenko in https://github.com/notaryproject/notation/pull/1249
* backport: from main to release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation/pull/1267
**Full Changelog**: https://github.com/notaryproject/notation/compare/v1.3.1...001cc919603c1dc16c6aad387c94b4209cb9c901
Please review the PR and vote by approving.
> bump: release v1.3.2

- test/e2e/suite/command/blob/sign.go
- test/e2e/suite/command/sign.go
- test/e2e/suite/plugin/install.go
The current invalid urls in e2e tests may cause the test to fail occasionally.
> fix: fix e2e test urls

- internal/version/version.go
- test/e2e/suite/command/sign.go
- test/e2e/suite/plugin/install.go
This PR targets on the `release-1.3` branch.
After the vote PR https://github.com/notaryproject/notation/pull/1268 been merged, the e2e test on the release-1.3 branch is failing.
This is due to a bug on the e2e test, which did not pop up before the merge. Hence creating this new PR to fix it.
> fix: increase e2e test stability on release-1.3 branch

- cmd/notation/internal/verify/verify.go
This PR fixes issue highlighted by `staticcheck` - using deprecated constructs.
It partially addresses https://github.com/notaryproject/notation/issues/1256
> fix: fix linter complain, don't use deprecated types

- cmd/notation/version.go
- specs/cmd/version.md
Pending on https://github.com/notaryproject/notation/pull/1260
Example of notation version command
```
Notation - a tool to sign and verify artifacts.
Version:     v2.0.0-alpha.1+unreleased
Go version:  go1.24.0
OS/Arch:     linux/amd64
Git commit:  c68425f82871c27140a5c1b259b518750e558446
```
Resolve part of #1247
> fix: add os/arch in version command

- cmd/notation/internal/flag/options.go
- specs/cmd/blob.md
- specs/cmd/certificate.md
- specs/cmd/inspect.md
- specs/cmd/key.md
- specs/cmd/list.md
- specs/cmd/login.md
- specs/cmd/logout.md
- specs/cmd/plugin.md
- specs/cmd/sign.md
- specs/cmd/verify.md
- specs/error-handling-guideline.md
- test/e2e/suite/command/inspect.go
- test/e2e/suite/command/list.go
- test/e2e/suite/command/sign.go
- test/e2e/suite/command/verify.go
- test/e2e/suite/plugin/install.go
- test/e2e/suite/trustpolicy/trust_store.go
- test/e2e/suite/trustpolicy/trusted_identity.go
- test/e2e/suite/trustpolicy/verification_level.go
Pending on https://github.com/notaryproject/notation/pull/1260
This PR removed the `--verbose` flag support as proposed in https://github.com/notaryproject/notation/pull/1260.
Resolve part of #1247
> fix!: remove the --verbose flag for all related commands

- specs/proposals/diagnostic-experience.md
Resolve #1247 
This proposal document aims to:
1. Identify the usability issues of the `--verbose` and `--debug` options.
2. Clarify the concepts of different types of output and logs for diagnostic purposes.
3. List the guiding principles to write comprehensive, clear, and conducive debug output and debug logs for effective diagnosis.
4. Propose solutions to improve the diagnostic experience for `notation` CLI users and developers.
> docs: Improve Notation Diagnostic Experience
